services: 
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    tty: true
    networks:
      - app_network
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
      
  app:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: app
    tty: true
    networks:
      - app_network
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && npm run start"
    volumes: 
      - ./nodejs:/usr/src/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app_network

networks:
  app_network:
    driver: bridge